version: '3'
services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:14-alpine3.18
    environment:
      POSTGRES_DB: sem_5_task_2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123